### ISSUE TITLE
Build break in Point Cloud Library (PCL) plugin

### ISSUE THREAD

**Issue by takaomoriyama** [watson-intu/self-plugins#3]
After the following commit, self-plugins cause build error.
```
commit bcca080a5f6e7e8f2523649364490b771cbbeffd
Author: Hide Muta <hide.muta@au1.ibm.com>
Date:   Mon Jul 10 12:52:53 2017 +0800

    Clustring based object detector
```

Here is build log.

```
...
[ 66%] Building CXX object plugins/pcl/CMakeFiles/pcl_plugin.dir/services/PCLObjectRecognition.cpp.o
[ 66%] Building CXX object plugins/pcl/CMakeFiles/pcl_plugin.dir/tests/TestPCLObjectRecogntion.cpp.o
In file included from /Users/moriyama/dev/watson-intu/self2/plugins/pcl/tests/TestPCLObjectRecogntion.cpp:23:
/Users/moriyama/dev/watson-intu/self2/plugins/pcl/./services/PCLObjectRecognition.h:26:10: fatal error: 'pcl/visualization/pcl_visualizer.h' file not found
#include <pcl/visualization/pcl_visualizer.h>
         ^
In file included from /Users/moriyama/dev/watson-intu/self2/plugins/pcl/services/PCLObjectRecognition.cpp:21:
/Users/moriyama/dev/watson-intu/self2/plugins/pcl/services/PCLObjectRecognition.h:26:10: fatal error: 'pcl/visualization/pcl_visualizer.h' file not found
#include <pcl/visualization/pcl_visualizer.h>
         ^
1 error generated.
``

**Comment by hidemuta** [comment]
I've applied fix for this build error.
The visualization staff was not completely excluded from the code. Sorry.

**Comment by takaomoriyama** [comment]
Muta-san,

We have a governance rule for Intu code described in https://github.com/watson-intu/self/blob/develop/contributing.md. Please take a look before updating the code directly.

Desired procedure was as follows:
1. You create a fork of the repository.
2. Create fix for the issue, and verify it.
3. Create a pull request for the fix.
Please include a sentence "Signed-off-by: <Your full name> <Your mail address>" in the comment field of the pull request, or in the commit message to indicate the origin the certificate of origin. See https://github.com/watson-intu/self/blob/develop/contributing.md for details.
4. Someone in the administrator team will review and verify the code, and may approve.
5. Having no objection to the code for 48 hours, one of the administrator team will merge the code to the repository.

Thank you for your cooperation.

**Comment by takaomoriyama** [comment]
Muta-san applied a fix for build break as:
```
commit bcca080a5f6e7e8f2523649364490b771cbbeffd
Author: Hide Muta <hide.muta@au1.ibm.com>
Date:   Mon Jul 10 12:52:53 2017 +0800

    Clustring based object detector

**Comment by hidemuta** [comment]
Thanks so much for recovering the lost commit completely.

**Comment by takaomoriyama** [comment]
The snapshot 6b996b474ca5fbd05eb76314731a139ee8e5d2fa, including the fix for build break on new PCL code, has been recovered.
